### ISSUE TITLE
Add support for Windows XP

### ISSUE THREAD

**Issue by Mogar171** [YetiBots/Warcraft#14]
Hello
When I try to open .exe file I get the message "Application WildCatch.exe is not a valid Win32 application". I use Windows XP SP3 x86, .NET Framework 4.0. Can you make a version that will be supported by this system?
Thanks

**Comment by YetiBots** [comment]
Hi, as of April 8, 2014, Windows XP has reached end of life and should no longer be used. Windows Vista is receiving the same fate April 11, 2017. In order to make the development life-cycle simpler, we have decided to only support 64-bit versions of Windows 7 and above. Please consider upgrading your system if you would like to use Yeti-Bots products.
