### ISSUE TITLE
sorry to post it here

### ISSUE THREAD

**Issue by Goten87** [YetiBots/Warcraft#18]
hello yetibots
i wanne find a good fishing bot and i googled it and came out with your bot on the top
so now my question is how can i be sure you are not a keylogger as well
sins we need internet

i had a bot back in the day and all my game accounts where hacked when i used it it installed a keylogger on my pc as well

are u just a exe file that i can use with no install at all or do i need to install the program
also i will like to have like player feedback on the website what people think that used it alrdy
that way when the feedback is good people will download it sooner

Greets Goten87

**Comment by YetiBots** [comment]
Hi, we have zero interest in targeting end-users and stealing their accounts. This is why we've made every effort to tell you exactly what we're doing and why. If you are concerned about Yeti-Bots applications installing low-level hooks, you can always start the applications with the `-nohook` command-line parameter. That being said, just because we don't want to hack you doesn't mean others don't, so keep your guard up.

Each application is just a single executable (and any files it creates). Files associated with the Yeti-Bots application will always appear in the same folder as the exe. These include your settings as well as your other data, such as Sonar filters. We don't explicitly write to the registry.

We gather a lot of feedback on [OwnedCore](http://www.ownedcore.com/), that's the best place to go. As for feedback on the website, that would only really be useful if we wanted to maximize our profit, which is non-existent because the applications are free. People either use them and like them or they don't. We just focus on creating a product we can be proud of.
